"""
github_pr.py - GitHub API interactions: branch creation, file updates, PR creation.

Uses PyGithub. Requires GITHUB_TOKEN and GITHUB_REPOSITORY env vars.

One PR per scan: a single branch is created, all fixed files are committed onto it,
and one pull request is opened targeting the entire run's SonarQube rule.
"""

import os
import uuid

from github import Github, GithubException
from github.Repository import Repository

from .scanner import Issue


def _get_repo() -> Repository:
    token = os.environ["GITHUB_TOKEN"]
    repo_name = os.environ["GITHUB_REPOSITORY"]
    return Github(token).get_repo(repo_name)


def ensure_labels(repo: Repository) -> None:
    """Create labels used by RASS Scavenger if they don't exist yet."""
    labels_to_ensure = [
        ("rass-scavenger", "0075ca", "Auto-generated by RASS Scavenger bot"),
        ("reliability", "e4e669", "Reliability improvement"),
        ("auto-fix", "d93f0b", "Automated fix — please review carefully"),
    ]
    existing = {lbl.name for lbl in repo.get_labels()}
    for name, color, description in labels_to_ensure:
        if name not in existing:
            try:
                repo.create_label(name=name, color=color, description=description)
            except GithubException:
                pass  # Race condition — label was created between our check and create


def create_fix_pr(
    file_fixes: list[dict],
    target_rule: str,
    pr_body: str,
) -> str:
    """
    Create a single branch, commit every fixed file onto it, and open one PR.

    Args:
        file_fixes: list of dicts, each with keys:
                      filepath     — repo-relative path (str)
                      fixed_source — new file content (str)
                      issues       — all Issue objects detected in this file
                      fixed_issue  — the specific Issue that was fixed
        target_rule: SonarQube rule ID being fixed across all files (e.g. "S2095")
        pr_body:     markdown body for the pull-request description

    Returns the HTML URL of the created PR.
    """
    if not file_fixes:
        raise ValueError("file_fixes must not be empty")

    repo = _get_repo()
    ensure_labels(repo)

    default_branch = repo.default_branch
    base_sha = repo.get_branch(default_branch).commit.sha

    # Unique branch name scoped to the rule to avoid collisions on reruns
    short_id = uuid.uuid4().hex[:8]
    safe_rule = target_rule.lower().replace(" ", "-")
    branch_name = f"rass-scavenger/{safe_rule}-{short_id}"

    # Create the branch from the current HEAD of the default branch
    repo.create_git_ref(f"refs/heads/{branch_name}", base_sha)

    # Commit each fixed file individually onto the new branch
    for fix in file_fixes:
        filepath: str = fix["filepath"]
        fixed_source: str = fix["fixed_source"]
        fixed_issue: Issue = fix["fixed_issue"]

        # Fetch the current blob SHA so GitHub accepts the update
        try:
            file_obj = repo.get_contents(filepath, ref=default_branch)
            file_sha = file_obj.sha
        except GithubException as exc:
            raise RuntimeError(f"Could not fetch {filepath} from GitHub: {exc}") from exc

        commit_msg = (
            f"fix(reliability): [{target_rule}] {fixed_issue.check_type} "
            f"at line {fixed_issue.line} in {filepath}\n\n"
            "Generated by RASS Scavenger — review before merging."
        )

        repo.update_file(
            path=filepath,
            message=commit_msg,
            content=fixed_source,
            sha=file_sha,
            branch=branch_name,
        )

    # Build a concise PR title (GitHub truncates beyond ~72 chars)
    file_count = len(file_fixes)
    check_type = file_fixes[0]["fixed_issue"].check_type
    title = f"fix(reliability): [{target_rule}] {check_type} — {file_count} file(s)"
    if len(title) > 72:
        title = f"fix(reliability): [{target_rule}] {file_count} file(s) auto-fixed"

    pr = repo.create_pull(
        title=title,
        body=pr_body,
        head=branch_name,
        base=default_branch,
        draft=False,
    )

    try:
        pr.add_to_labels("rass-scavenger", "reliability", "auto-fix")
    except GithubException:
        pass  # Labels may not exist despite ensure_labels attempt

    return pr.html_url
