"""
github_pr.py - GitHub API interactions: branch creation, file updates, PR creation.

Uses PyGithub. Requires GITHUB_TOKEN and GITHUB_REPOSITORY env vars.
"""

import os
import uuid

from github import Github, GithubException
from github.Repository import Repository

from .scanner import Issue


def _get_repo() -> Repository:
    token = os.environ["GITHUB_TOKEN"]
    repo_name = os.environ["GITHUB_REPOSITORY"]
    return Github(token).get_repo(repo_name)


def ensure_labels(repo: Repository) -> None:
    """Create labels used by RASS Scavenger if they don't exist yet."""
    labels_to_ensure = [
        ("rass-scavenger", "0075ca", "Auto-generated by RASS Scavenger bot"),
        ("reliability", "e4e669", "Reliability improvement"),
        ("auto-fix", "d93f0b", "Automated fix — please review carefully"),
    ]
    existing = {lbl.name for lbl in repo.get_labels()}
    for name, color, description in labels_to_ensure:
        if name not in existing:
            try:
                repo.create_label(name=name, color=color, description=description)
            except GithubException:
                pass  # Race condition — label was created between our check and create


def create_fix_pr(
    filepath: str,
    fixed_source: str,
    issues: list[Issue],
    pr_body: str,
) -> str:
    """
    Create a branch, commit the fixed file, and open a draft PR.

    Returns the HTML URL of the created PR.
    """
    repo = _get_repo()
    ensure_labels(repo)

    default_branch = repo.default_branch
    base_sha = repo.get_branch(default_branch).commit.sha

    # Unique branch name to avoid collisions on reruns
    short_id = uuid.uuid4().hex[:8]
    branch_name = f"rass-scavenger/reliability-{short_id}"

    # Create branch
    repo.create_git_ref(f"refs/heads/{branch_name}", base_sha)

    # Get current file SHA (needed to update)
    try:
        file_obj = repo.get_contents(filepath, ref=default_branch)
        file_sha = file_obj.sha
    except GithubException as exc:
        raise RuntimeError(f"Could not fetch {filepath} from GitHub: {exc}") from exc

    commit_msg = (
        f"fix(reliability): auto-fix {len(issues)} issue(s) in {filepath}\n\n"
        "Generated by RASS Scavenger — review before merging."
    )

    repo.update_file(
        path=filepath,
        message=commit_msg,
        content=fixed_source,
        sha=file_sha,
        branch=branch_name,
    )

    # Short title (GitHub truncates at ~72 chars)
    check_names = ", ".join(sorted({i.check_type for i in issues}))
    title = f"fix(reliability): {filepath} [{check_names}]"
    if len(title) > 72:
        title = f"fix(reliability): {filepath} — {len(issues)} reliability fix(es)"

    pr = repo.create_pull(
        title=title,
        body=pr_body,
        head=branch_name,
        base=default_branch,
        draft=False,
    )

    try:
        pr.add_to_labels("rass-scavenger", "reliability", "auto-fix")
    except GithubException:
        pass  # Labels may not exist despite ensure_labels attempt

    return pr.html_url
